"""empty message

Revision ID: 111cebe7dbeb
Revises: 576e55a97c96
Create Date: 2016-05-29 23:28:31.211176

"""

# revision identifiers, used by Alembic.
revision = '111cebe7dbeb'
down_revision = '576e55a97c96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorships', sa.Column('just_test', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorships', 'just_test')
    ### end Alembic commands ###
