"""empty message

Revision ID: 3fa3eca4d8a7
Revises: 
Create Date: 2018-01-01 06:54:43.640768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa3eca4d8a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('common_name', sa.String(length=80), nullable=False),
    sa.Column('scientific_name', sa.String(length=80), nullable=False),
    sa.Column('family', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('coord_utm_e', sa.Float(), nullable=True),
    sa.Column('coord_utm_n', sa.Float(), nullable=True),
    sa.Column('coord_utm_zone_n', sa.Integer(), nullable=True),
    sa.Column('coord_utm_zone_letter', sa.String(), nullable=True),
    sa.Column('coord_lat', sa.Float(), nullable=True),
    sa.Column('coord_lon', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('circ', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('observation', sa.String(length=500), nullable=True),
    sa.Column('surveyed_on', sa.DateTime(), nullable=True),
    sa.Column('base_area', sa.Float(), nullable=True),
    sa.Column('size_class', sa.String(length=80), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('phenology', sa.String(length=500), nullable=True),
    sa.Column('relevance', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sponsored_on', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('just_test', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsorships')
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('trees')
    # ### end Alembic commands ###
