"""empty message

Revision ID: 576e55a97c96
Revises: e90bd0aada2f
Create Date: 2016-05-29 05:50:33.209855

"""

# revision identifiers, used by Alembic.
revision = '576e55a97c96'
down_revision = 'e90bd0aada2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorships', sa.Column('status', sa.Enum(['pending', 'confirmed', 'cancelled']), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorships', 'status')
    ### end Alembic commands ###
