"""empty message

Revision ID: da14d9b768fa
Revises: 43b8a252a5ff
Create Date: 2017-12-31 12:57:20.821990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da14d9b768fa'
down_revision = '43b8a252a5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_column('sponsored_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsored_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
